<a href="https://colab.research.google.com/github/ditiansm2015/Python-and-SQL/blob/main/Python_Questions_Notebook_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Adding two numpy array using loop**

In [ ]:
# Creating two random numpy arrays
import numpy as np

array1 = np.random.rand(5,4)
array2 = np.random.rand(5,4)

print(array1)
print(array2)

[[0.85480684 0.52184761 0.42962647 0.78400042]
 [0.21094468 0.61320302 0.41339101 0.9545601 ]
 [0.9138918  0.22388466 0.10123629 0.57853493]
 [0.98533181 0.76292369 0.11752807 0.16672167]
 [0.01002588 0.31709559 0.93439987 0.34861927]]
[[0.49383435 0.32863119 0.13757335 0.69092435]
 [0.41341327 0.72786916 0.87519847 0.39438488]
 [0.26433316 0.33112614 0.660533   0.38223913]
 [0.65922774 0.83489352 0.62977463 0.84018067]
 [0.24592739 0.60065996 0.88639484 0.72269053]]


In [ ]:
# Addition here

for i in range(len(array1)):
  for j in range(len(array2)):
    sum[i-1,j-1] =  array1[i-1,j-1] + array2[i-1,j-1]
                             
print(sum)


[[1.00201986 1.28814039 0.94271596 0.63773539]
 [0.41887672 1.77479894 1.05727985 0.47595475]
 [0.78509109 0.99672039 0.80806979 0.7330168 ]
 [0.59219261 0.76224853 1.02687073 1.20710085]
 [0.97921664 0.94407181 1.42712726 1.58400744]]


In [ ]:
# Optimized Addition here
#Create the sum matrix beforehand

sum = np.zeros((5,4))

for i in range(len(array1)):
  for j in range(len(array2)):
    sum[i-1,j-1] =  array1[i-1,j-1] + array2[i-1,j-1]

                              
print(sum)


[[1.00201986 1.28814039 0.94271596 0.63773539]
 [0.41887672 1.77479894 1.05727985 0.47595475]
 [0.78509109 0.99672039 0.80806979 0.7330168 ]
 [0.59219261 0.76224853 1.02687073 1.20710085]
 [0.97921664 0.94407181 1.42712726 1.58400744]]


**Find if a given point is inside or outside a circle**

In [ ]:
# Input circle centres and radius
cx,cy,r = input("Enter centre of Circle (x,y) and radius of circle all seperated by space ").split()
cx,cy,r = int(cx),int(cy),int(r)
print(cx, ",", cy, ",", r)

# Input point that need to be validated
px, py = input("Enter the point that need to be checked if it is inside or outside circle ").split()
px, py= int(px),int(py)
print(px, ",", py)

# points can be converted into int in the following was as well
# px,py = [int(x) for x in [px,py]]

Enter centre of Circle (x,y) and radius of circle all seperated by space 2 3 5
2 , 3 , 5
Enter the point that need to be checked if it is inside or outside circle 3 6
3 , 6


In [ ]:
# Checking if the point is inside or outside circle

import math
distance = math.sqrt((cx- px)**2 + (cy - py)**2)

print("Distance of circle centre from point is ", distance, " while radius is ",r)

if distance > r:
  print("Point is outside circle")

elif distance == r:
  print("Point is on circle")

else :
  print("Point is inside circle")


Distance of circle centre from point is  3.1622776601683795  while radius is  5
Point is inside circle
